# Generated by Django 5.2.7 on 2025-11-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_end_time_remove_event_start_time_and_more'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={},
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='slot',
            table=None,
        ),
    ]
