# Generated by Django 5.2.7 on 2025-11-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_options_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendees_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
